docs: add new argoproj maintainers
argoproj/argoproj pull request #105
Opened 2022-01-21 00:24 UTC by alexmt

Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

2022-01-21 00:29 UTC, hblixt requested changes

2022-01-21 00:29 UTC, hblixt commented on MAINTAINERS.md
> +| Hari Rongali | [harikrongali](https://github.com/harikrongali) | Reviewer - Events | [Intuit](https://www.github.com/intuit/) | Yes |
This should be Rollouts.

2022-01-21 00:29 UTC, hblixt commented on MAINTAINERS.md
> +| Daniel Soifer | [daniel-codefresh](https://github.com/daniel-codefresh) | Reviewer - Events Argo Events | [Codefresh](https://www.github.com/codefresh/) | Yes |
Typo  - Should be just "Events"

2022-01-21 00:33 UTC, alexmt commented on MAINTAINERS.md
> +| Hari Rongali | [harikrongali](https://github.com/harikrongali) | Reviewer - Events | [Intuit](https://www.github.com/intuit/) | Yes |
thank you! fixed

2022-01-21 00:33 UTC, alexmt commented on MAINTAINERS.md
> +| Daniel Soifer | [daniel-codefresh](https://github.com/daniel-codefresh) | Reviewer - Events Argo Events | [Codefresh](https://www.github.com/codefresh/) | Yes |
fixed

2022-01-26 21:43 UTC, edlee2121 approved these changes

2022-01-26 22:26 UTC, hblixt approved these changes

2022-01-26 22:46 UTC, merged