Add Zach Aller to SIG Security doc
argoproj/argoproj pull request #189
Opened 2023-02-02 15:08 UTC by crenshaw-dev

Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>

2023-02-15 05:46 UTC, hblixt requested changes

2023-02-15 05:46 UTC, hblixt commented on sigs/sig-security/README.md
> +| [Alexander Matyushentsev](https://github.com/alexmt)    | Intuit    |                             |
Alex should be Akuity.

2023-03-01 18:50 UTC, sbose78 commented on sigs/sig-security/README.md
> +| [Alexander Matyushentsev](https://github.com/alexmt)    | Intuit    |                             |
done.

2023-03-01 18:51 UTC, sbose78 approved these changes

2023-07-27 18:33 UTC, merged