add issue templates for promotion
argoproj/argoproj pull request #191
Opened 2023-02-02 19:35 UTC by crenshaw-dev

I've created Reviewer and Approver promotion templates, since those are relatively easy to evaluate.

I'll leave adding a Lead template as a future task. That one's more difficult, because the requirements lend themselves less to a checklist-style template.

2023-02-02 20:47 UTC, rohankmr414 requested changes

2023-02-02 20:47 UTC, rohankmr414 commented on .github/ISSUE_TEMPLATE/promotion-reviewer.md
> +- [ ] Argo Events
typo?
```suggestion
- [ ] Argo Workflows
```

2023-02-02 20:47 UTC, rohankmr414 commented on .github/ISSUE_TEMPLATE/promotion-approver.md
> +- [ ] Argo Events
typo?
```suggestion
- [ ] Argo Workflows
```

2023-04-03 15:24 UTC, crenshaw-dev commented on .github/ISSUE_TEMPLATE/promotion-approver.md
> +
```suggestion

<!--
IMPORTANT: A request for promotion to Approver should be initiated by an Approver or a Lead. After the Approver or Lead recommends promotion, the nominee should fill out this template and open an issue, listing the initiator as one of their sponsors.
-->

```

2023-04-04 15:32 UTC, terrytangyuan approved these changes
+1

2023-04-04 15:37 UTC, sbose78 approved these changes
Looks simple yet an effective way to propose a promotion.

2023-04-26 18:59 UTC, merged