scoped reviewers not considered maintainers
argoproj/argoproj pull request #219
Opened 2023-07-20 13:49 UTC by crenshaw-dev

2023-07-20 15:17 UTC, terrytangyuan reviewed
Are you planning to use CODEOWNERS to request scoped reviews?

2023-07-20 15:51 UTC, csantanapr requested changes
this change is negative one, with no reasoning or open discussion written down

2023-07-20 15:51 UTC, csantanapr commented on community/membership.md
> +
This NOTE by itself as is written, it feels like gate keeping, creating friction and making it more difficult 
for a contributor to be recognize as a CNCF project maintainer or CNCF Argo project maintainer, which
there should not be any distinction because "Argo" is a CNCF project. 

I think the contribution ladder you have in Argo is simple and clear.
You are first a [member](I am actively contributing to 1 or more Argoproj subprojects) which requires "actively contributing to 1 or more Argoproj subprojects",
and many other requirements including trusted by 2 sponsors:

Being a "member" you are not a maintainer, yet

Next level is [reviewer](https://github.com/argoproj/argoproj/blob/master/community/membership.md#reviewer) which requires to meet a active contributions and knowledge to be able
to provide high quality feedback and guidance on PRs.
The main requirements already including the ones from being a member for at least 3 months are:
- Active community participation (meetings, slack, stack overflow) and interact with issues for at least 1 month.
- Reviewer for or author of at least 5 substantial PRs to the codebase, with the
  definition of substantial subject to the lead's discretion (e.g.
  refactors, enhancements rather than grammar correction or one-line pulls).
- Knowledgeable about the codebase
- Sponsored by a subproject lead
  - With no objections from other leads

I think this is a bar to meet for someone to be consider a CNCF project maintainer, or Argo maintainer. By being a good reviewers and active contributing as a member, take into account
that the requirements states "or author of at least 5 substantial PRs" so someone could be
a review with substantial PRs contributions and you are going to preven this person from being
recognize as a maintainer.

Take into account that a large subproject like ArgoCD, you can't expect every maintainer to
be a subject matter expert providing high quality reviews on every single area of the subproject,
there would be people that would focus on docs, others on app controller, others on ui, others on 
repo server, others on scalability and observability, or common packages.

My two cents are if someone can meet the bar to be reviewer, even if its a portion of the subproject
should be recognize as a maintainer. and not do the distinction between some reviewers will be
maintainers and some others not, and be subjective to human judgement.

2023-07-20 19:50 UTC, crenshaw-dev commented
@terrytangyuan yep! @34fathombelow and I are working on a PoC in another repo, just to make sure we can enforce the likely scopes (e.g. docs).

2023-07-24 04:38 UTC, agilgur5 commented on community/membership.md
> +
Yea, I just stumbled upon this PR and literally the first thing I thought about the current wording was that it sounded like gate-keeping.

The current wording also conflicts with the current definition of Reviewer, which is _explicitly_ a "scoped" reviewer:
> some part of a subproject.
> Reviewer status is scoped to a part of the codebase.

It should also be made more clear somewhere what "maintainer" status entails. As far as I can tell, it is primarily about voting status?

2023-08-14 15:41 UTC, crenshaw-dev commented
Agree with the posted concerns!

2023-08-14 15:41 UTC, closed without merging