Argoproj promotions/membership
argoproj/argoproj pull request #342
Opened 2024-11-11 18:21 UTC by crenshaw-dev

# Argoproj promotions/membership

Every quarter, the Argoproj maintainers review requests for project membership and promotions (read about the roles [here](https://github.com/argoproj/argoproj/blob/master/community/membership.md#community-membership)). The changes below recognize the incredible efforts and commitment to the project by these people. Thank you so much!

## 🚀  Maintainer promotions

Congrats to the following contributors for their promotion:

* Alan Clucas (@Joibel) to Lead in Argo Workflows
* Shuangkun Tian (@shuangkun) to Approver in Argo Workflows
* Ryan Umstead (@rumstead) to Approver in Argo CD
* @jswxstw to Reviewer in Argo CD
* Regina Voloshin (@reggie-k)  to Reviewer in argo CD

## ⭐  New members

An additional congratulations to the following folks for becoming Argoproj members:

- chengjoey (@chengjoey)
- Siddhesh Ghadi (@svghadi)
- 변재한 (@jaehanbyun)
- Anand Francis Joseph (@anandf)
- Andrii Korotkov (@andrii-korotkov)
- Nitish Kumar (@nitishify)
- Kunho Lee (@daengdaengLee)
- leehosu (@leehosu)
- Mason Malone (@MasonM)
- nueavv (@nueavv)
- Linghao Su (@linghaoSu)

You all will receive invitations on GitHub to become members of the Argoproj organization.

## 🎓 Alumni

The maintainers document contains a new section for folks who were previously maintainers but have been inactive for at least a year. While not currently active, they deserve continued recognition for their impact on the project!

Closes #321 
Closes #322 
Closes #323 
Closes #324
Closes #326 
Closes #327 
Closes #328 
Closes #329 
Closes #330 
Closes #333 
Closes #334 
Closes #337 
Closes #338 
Closes #339

2024-11-11 20:31 UTC, Joibel requested changes

2024-11-11 20:31 UTC, Joibel commented on MAINTAINERS.md
> +| Shuangkun Tian            | [shuangkun](https://github.com/shuangkun)               | Approver - Workflows                                   | Alibaba                                              |
We did not agree on a promotion to approver for Shangkun at this time, can you remove this one please.

2024-11-25 16:18 UTC, rumstead commented
@Joibel  / @crenshaw-dev should we get this updated and merged?

2024-11-25 17:05 UTC, crenshaw-dev commented
@Joibel ptal

2024-11-25 17:39 UTC, Joibel approved these changes
LGTM

2024-11-25 17:54 UTC, merged

2024-11-27 00:09 UTC, terrytangyuan commented
Congratulations everyone!